### ISSUE TITLE
Feature Request: Only Approve a specific run's jobs

### ISSUE THREAD

**Issue by mcascone** [activescott/automate-environment-deployment-approval#60]
Hi, is there a way to only approve a specific run's jobs? If I run this action in a repo with multiple active jobs, with deploys waiting for approval, they'll _all_ be approved when it fires. But I only want to approve the deploy from the workflow that I called the action from.

Is this possible? If not, please consider this a feature request! Thank you!

(Also relates to #59)

**Comment by activescott** [comment]
It is designed to fetch fetch ALL pending deploys/runs and approve them. This is done at https://github.com/activescott/automate-environment-deployment-approval/blob/e84337cb8d57f43a58b5490c55ef0b5c446101f2/src/approver.ts#L13

However, as for a feature request... 
The action already accepts `environment_allow_list` and `actor_allow_list` to allow "filtering" which runs it approves. We could add an _optional_ `run_id_allow_list` so that a workflow could call it and pass that ID in. If a value is provided for it, then the action would only approve the ones with the specified run ID.

If that meets your needs, I am happy to accept a PR. I am also happy to advise or even pair on it if you need a hand. Just let me know how to help.

 A couple of notes for future reference:
 - inputs are specified at https://github.com/activescott/automate-environment-deployment-approval/blob/e84337cb8d57f43a58b5490c55ef0b5c446101f2/action.yml#L9
 - The filtering of a run id could be done alongside the others in `filterDeploymentsToApprove` at https://github.com/activescott/automate-environment-deployment-approval/blob/main/src/approver.ts#L91

**Comment by augustodileo** [comment]
Gonna create a PR for this even tho im not a typescript dev

**Comment by augustodileo** [comment]
https://github.com/activescott/automate-environment-deployment-approval/pull/63

Created a PR, I know this sounds silly but my experience in TS is null so I dont know even how to test this modifications made with Copilot.

Hope it helps

**Comment by activescott** [comment]
Thanks to @augustodileo for contributing this feature. Please test it out with the latest release (https://github.com/activescott/automate-environment-deployment-approval/releases/tag/v1.1.0) and let me know if you have success or encounter any issues
